jobs:
    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: daily-verify
        - IN: daily-verify-asserts
        - IN: zephyr_ciRepo
        - IN: coverity-token
        - IN: s3-token

    - name: zephyr-testing_runCI
      type: runCI
      steps:
        - IN: zephyr-testing_ciRepo
        - IN: coverity-token
        - IN: s3-token
