jobs:
    - name: ci-test_runCI
      type: runCI
      steps:
        - IN: daily-verify
        - IN: ci-test_ciRepo
        - IN: coverity-token
        - IN: s3-token

    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: daily-verify
        - IN: zephyr_ciRepo
        - IN: coverity-token
        - IN: s3-token

    - name: zephyr-testing_runCI
      type: runCI
      steps:
        - IN: zephyr-testing_ciRepo
        - IN: coverity-token
        - IN: s3-token


    - name: report
      type: runSh
      steps:
        - IN: s3-token
        - IN: zephyr-testing_runCI
        - TASK:
          - script: env

    - name: zephyr-daily-doc
      type: runSh
      steps:
        - IN: s3-token
        - IN: main_repo
          switch: off
        - IN: docs_theme_repo
          switch: off
        - IN: daily-docs
        - TASK:
          - script: . /build/IN/main_repo/gitRepo/scripts/ci/build-docs.sh
