jobs:
    - name: meta-zephyr-sdk_runCI
      type: runCI
      steps:
        - IN: s3-token
        - IN: meta-zephyr-sdk_ciRepo

    - name: create_sdk
      type: runSh
      steps:
        - IN: s3-token
        - IN: meta-zephyr-sdk_ciRepo
        - IN: meta-zephyr-sdk_runCI
        - TASK:
          - script: >
              if [ "${IS_GIT_TAG}" = "true"]; then
                export S3_PATH="s3://incoming.zephyrproject.org/sdk/${METAZEPHYRSDK_CIREPO_VERSIONNUMBER}";
                sudo apt-get install -y makeself p7zip-full cpio tree;
                sudo pip install awscli;
                aws s3 sync ${S3_PATH}/toolchains/ toolchains;
                chmod +x toolchains/*.sh;
                cp toolchains/make_zephyr_sdk.sh toolchains/template_dir .;
                sh ./make_zephyr_sdk.sh;
                aws s3 cp zephyr-sdk* ${S3_PATH}/;
              fi

    - name: ci-test_runCI
      type: runCI
      steps:
        - IN: daily-verify-debug
        - IN: daily-verify
        - IN: daily-verify-arm
        - IN: daily-verify-issm
          #- IN: code-scan
        - IN: ci-test_ciRepo
        - IN: s3-token

    - name: zephyr_runCI
      type: runCI
      steps:
        - IN: zephyr_ciRepo
        - IN: s3-token

    - name: zephyr-testing_runCI
      type: runCI
      steps:
        - IN: zephyr-testing_ciRepo


    - name: zephyr-daily-doc
      type: runSh
      steps:
        - IN: s3-token
        - IN: main_repo
          switch: off
        - IN: ci_test_repo
          switch: off
        - IN: docs_theme_repo
          switch: off
        - IN: daily-docs
        - TASK:
          - script: sudo apt-get install doxygen make
          - script: sudo pip install breathe==4.6.0 sphinx==1.5.5  awscli sphinx_rtd_theme
          - script: . /build/IN/ci_test_repo/gitRepo/scripts/build-docs.sh

    - name: project-doc
      type: runSh
      steps:
        - IN: s3-token
        - IN: doc_repo
          switch: off
        - IN: docs_theme_repo
          switch: off
        - TASK:
          - script: sudo apt-get install doxygen make
          - script: sudo pip install breathe==4.6.0 sphinx==1.5.5  awscli sphinx_rtd_theme
          - script: cd /build/IN/doc_repo/gitRepo/
          - script: cp -a /build/IN/docs_theme_repo/gitRepo/ themes/zephyr-docs-theme
          - script: make html
          - script: aws s3 sync --quiet  _build/html s3://docs.zephyrproject.org/

    - name: test-shippable_runCI
      type: runCI
      steps:
        - IN: res-state
        - OUT: res-state

    - name: test_shippable_final
      type: runSh
      steps:
        - IN: test-shippable_runCI
        - IN: res-state
        - TASK:
          - script: |
                env
                sudo apt-get install -y tree
                tree
                cat /build/IN/test-shippable_runCI/runCI/sdk.env
        - OUT: res-state
